services:
    nsm-api:
        build: .
        ports:
            - '9200:9200'
        restart: always
        volumes:
            - type: bind
              source: /media/drive3/persistence/nsm/
              target: /etc/nsm/
            - type: bind
              source: /webapps
              target: /webapps
            - type: bind
              source: /etc/nsmexec
              target: /etc/nsmexec
